<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EPINHYDW00B1" name="calculator.CalulatorTest.CalculatorTesting" tests="92" failures="21" timestamp="2020-02-26T12:53:58 IST" time="0.245" errors="4">
  <testcase name="testSubForLong" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testDivForLong" time="0.037" classname="calculator.CalulatorTest.CalculatorTesting">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
[public void calculator.CalulatorTest.CalculatorTesting.testDivForLong(long,long,long)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testDivForLong([Parameter{index=0, type=long, declaredAnnotations=[]}, Parameter{index=1, type=long, declaredAnnotations=[]}, Parameter{index=2, type=long, declaredAnnotations=[]}])
Arguments: [(java.lang.Double) 1.1,(java.lang.Integer) -1,(java.lang.Double) -1.1]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void calculator.CalulatorTest.CalculatorTesting.testDivForLong(long,long,long)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testDivForLong([Parameter{index=0, type=long, declaredAnnotations=[]}, Parameter{index=1, type=long, declaredAnnotations=[]}, Parameter{index=2, type=long, declaredAnnotations=[]}])
Arguments: [(java.lang.Double) 1.1,(java.lang.Integer) -1,(java.lang.Double) -1.1]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:925)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- testDivForLong -->
  <testcase name="testPow" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSubForDouble" time="0.016" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testMulForLong" time="0.003" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSin" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testIsNegative" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSubForLong" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testCtg" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [0.61736962378] but found [1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [0.61736962378] but found [1.0]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testCtg(CalculatorTesting.java:339)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testCtg -->
  <testcase name="testIsNegative" time="0.007" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSqrt" time="0.015" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testMulForLong" time="0.022" classname="calculator.CalulatorTest.CalculatorTesting">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
[public void calculator.CalulatorTest.CalculatorTesting.testMulForLong(long,long,long)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testMulForLong([Parameter{index=0, type=long, declaredAnnotations=[]}, Parameter{index=1, type=long, declaredAnnotations=[]}, Parameter{index=2, type=long, declaredAnnotations=[]}])
Arguments: [(java.lang.Double) 1.1,(java.lang.Integer) -1,(java.lang.Integer) -1]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void calculator.CalulatorTest.CalculatorTesting.testMulForLong(long,long,long)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testMulForLong([Parameter{index=0, type=long, declaredAnnotations=[]}, Parameter{index=1, type=long, declaredAnnotations=[]}, Parameter{index=2, type=long, declaredAnnotations=[]}])
Arguments: [(java.lang.Double) 1.1,(java.lang.Integer) -1,(java.lang.Integer) -1]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:925)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- testMulForLong -->
  <testcase name="testSubForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testCos" time="0.019" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [0.52532198881] but found [0.8509035245341184]">
      <![CDATA[java.lang.AssertionError: did not expect to find [0.52532198881] but found [0.8509035245341184]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testCos(CalculatorTesting.java:298)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testCos -->
  <testcase name="testMulForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSin" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testDivForDouble" time="0.007" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [0.0] but found [NaN]">
      <![CDATA[java.lang.AssertionError: did not expect to find [0.0] but found [NaN]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testDivForDouble(CalculatorTesting.java:188)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testDivForDouble -->
  <testcase name="testMulForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testPow" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testMulForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [-1.1] but found [-2.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [-1.1] but found [-2.0]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testMulForDouble(CalculatorTesting.java:143)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testMulForDouble -->
  <testcase name="testtg" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [-0.17883906379] but found [1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [-0.17883906379] but found [1.0]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testtg(CalculatorTesting.java:359)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testtg -->
  <testcase name="testMulForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testtg" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [1.33869021035] but found [1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [1.33869021035] but found [1.0]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testtg(CalculatorTesting.java:359)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testtg -->
  <testcase name="testPow" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testMulForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testMulForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testPow" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSubForLong" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testIsNegative" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testIsPositivity" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testCtg" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [-5.59161951959] but found [1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [-5.59161951959] but found [1.0]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testCtg(CalculatorTesting.java:339)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testCtg -->
  <testcase name="testSin" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testDivForLong" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSubForLong" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSubForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testDivForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testIsPositivity" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSin" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testtg" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [-1.99520041221] but found [1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [-1.99520041221] but found [1.0]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testtg(CalculatorTesting.java:359)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testtg -->
  <testcase name="testCtg" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [-0.74699881441] but found [-1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [-0.74699881441] but found [-1.0]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testCtg(CalculatorTesting.java:339)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testCtg -->
  <testcase name="testSumForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testCtg" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [5.59161951959] but found [-1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [5.59161951959] but found [-1.0]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testCtg(CalculatorTesting.java:339)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testCtg -->
  <testcase name="testSumForLong" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testDivForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSubForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSqrt" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSqrtForNegativeValues" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting">
    <error type="org.testng.TestException" message="
Method CalculatorTesting.testSqrtForNegativeValues()[pri:0, instance:calculator.CalulatorTest.CalculatorTesting@5abca1e0] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method CalculatorTesting.testSqrtForNegativeValues()[pri:0, instance:calculator.CalulatorTest.CalculatorTesting@5abca1e0] should have thrown an exception of type class java.lang.Exception
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:729)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:616)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- testSqrtForNegativeValues -->
  <testcase name="testCos" time="0.007" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [-0.59846006905] but found [-0.8011526357338304]">
      <![CDATA[java.lang.AssertionError: did not expect to find [-0.59846006905] but found [-0.8011526357338304]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testCos(CalculatorTesting.java:298)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testCos -->
  <testcase name="testDivForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testCos" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [0.98438195063] but found [-0.1760459464712114]">
      <![CDATA[java.lang.AssertionError: did not expect to find [0.98438195063] but found [-0.1760459464712114]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testCos(CalculatorTesting.java:298)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testCos -->
  <testcase name="testSumForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testCos" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [-0.44807361612] but found [0.8939966636005579]">
      <![CDATA[java.lang.AssertionError: did not expect to find [-0.44807361612] but found [0.8939966636005579]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testCos(CalculatorTesting.java:298)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testCos -->
  <testcase name="testSumForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testCtg" time="0.015" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [-0.50120278338] but found [1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [-0.50120278338] but found [1.0]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testCtg(CalculatorTesting.java:339)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testCtg -->
  <testcase name="testPow" time="0.004" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testMulForLong" time="0.002" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testPow" time="0.015" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testCtg" time="0.007" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [0.74699881441] but found [1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [0.74699881441] but found [1.0]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testCtg(CalculatorTesting.java:339)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testCtg -->
  <testcase name="testCos" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [-0.59846006905] but found [0.8011526357338304]">
      <![CDATA[java.lang.AssertionError: did not expect to find [-0.59846006905] but found [0.8011526357338304]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testCos(CalculatorTesting.java:298)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testCos -->
  <testcase name="testtg" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [1.61977519054] but found [1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [1.61977519054] but found [1.0]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testtg(CalculatorTesting.java:359)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testtg -->
  <testcase name="testSumForLong" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSin" time="0.015" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testMulForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSqrt" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSumForLong" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testDivForLong" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testIsPositivity" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testtg" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [0.17883906379] but found [1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [0.17883906379] but found [1.0]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testtg(CalculatorTesting.java:359)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testtg -->
  <testcase name="testDivForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testIsNegative" time="0.015" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSumForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [0.1] but found [0.10000000000000009]">
      <![CDATA[java.lang.AssertionError: did not expect to find [0.1] but found [0.10000000000000009]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testSumForDouble(CalculatorTesting.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testSumForDouble -->
  <testcase name="testMulForLong" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSumForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSubForDouble" time="0.016" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSqrt" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSubForLong" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testDivForLong" time="0.007" classname="calculator.CalulatorTest.CalculatorTesting">
    <error type="java.lang.NumberFormatException" message="Attempt to divide by zero">
      <![CDATA[java.lang.NumberFormatException: Attempt to divide by zero
at com.epam.tat.module4.Calculator.div(Calculator.java:34)
at calculator.CalulatorTest.CalculatorTesting.testDivForLong(CalculatorTesting.java:169)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- testDivForLong -->
  <testcase name="testSin" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSumForLong" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSumForLong" time="0.016" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testDivForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testPow" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSumForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testtg" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [-1.33869021035] but found [1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [-1.33869021035] but found [1.0]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testtg(CalculatorTesting.java:359)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testtg -->
  <testcase name="testSubForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testMulForLong" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testDivForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSubForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSumForDouble" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testCos" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting">
    <failure type="java.lang.AssertionError" message="did not expect to find [0.98438195063] but found [0.1760459464712114]">
      <![CDATA[java.lang.AssertionError: did not expect to find [0.98438195063] but found [0.1760459464712114]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at calculator.CalulatorTest.CalculatorTesting.testCos(CalculatorTesting.java:298)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testCos -->
  <testcase name="testSumForLong" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
  <testcase name="testSubForLong" time="0.000" classname="calculator.CalulatorTest.CalculatorTesting"/>
</testsuite> <!-- calculator.CalulatorTest.CalculatorTesting -->
